### ISSUE TITLE
logging.NullHandler not available under python 2.6

### ISSUE THREAD

**Issue by tonioo** [g2p/rfc6266#2]
This handler is available starting from python 2.7. The documentation says rfc6266 is compatible with python 2.6. Am I missing something?

Thanks.

**Comment by g2p** [comment]
Nope, the latest release broke python 2.6 to improve logging. Long term I'm not too interested in Py2.6 compatibility, but in this case it's a simple fix (except ImportError / do nothing would be acceptable).

**Comment by g2p** [comment]
v0.0.4 has a workaround.
